### PR TITLE
Add process stubs and update the files to be published

### PR DESCRIPTION
**Pull request by abhi18av**
@thorellk @emilio-r @boulund 

I've merged the solution for https://github.com/ctmrbio/BACTpipe/issues/132 with the [stub](https://www.nextflow.io/docs/edge/process.html#stub) feature which allows us to test the process flow and file operations without running the underlying softwares and opens up the way for faster iterations on the pipeline.

Just wanted to confirm one thing, you don't have any contstraints regarding updating the `nextflow` versions on your HPC right?

### CODE REVIEW

**Comment by thorellk** [comment]
Not as far as I am aware of 👍

**Comment by abhi18av** [comment]
@thorellk @emilio-r, before making further updates I'd just like to know whether you're able to upgrade your nextflow to latest edge release or not. Here are the instructions
https://github.com/ctmrbio/BACTpipe/pull/134#issuecomment-759504149

If you're not able to upgrade, I'll separate out the stub feature before the merge into `3.E` branch.

**Comment by thorellk** [comment]
I have now installed the edge version and it seems to work :)

**Comment by abhi18av** [comment]
Cool, I'm marking this as done now.

**Comment by abhi18av** [comment]
@thorellk , please take it forward with the merge :)

**Comment by abhi18av** [comment]
I'm merging it here so that this code makes it into the release PR on time.

**Pull request merged**
