### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by thorellk**
I guess we should then merge this to master so that we get all those changes included?

### CODE REVIEW

**Comment by abhi18av** [comment]
I recall that we've tested the individual PRs for the code in this `develop` branch. However, before the merge, would it be possible to test this PR as a whole with around 100 samples?

**Comment by emilio-r** [comment]
This was the branch that I used for #159, and all seemed fine then. But yes @abhi18av, I do agree that we should test with a larger set as well before merging. So, I will test this with a larger sample and then report back here when I have done so.

**Comment by boulund** [comment]
I'd like to see a mention in the changelog that we added retries as a workaround to the sendsketch process. Also, when releasing to the master branch, we should update the version number accordingly. So there are some more minor things that need to be updated before I feel this branch is ready to merge into master, can you help me get that sorted?

**Comment by emilio-r** [comment]
Having run this now, multiple times, on about 100 samples I am unfortunately once again seeing the skipping error. This time the skipped samples will fail thrice and then terminate the rest of the pipe. So, once a sample fails, it seems that it will fail all three attempts and then cancel the rest of the pipe. Again, the skipped samples are samples that we have previously run without fault through the pipe.

**Comment by boulund** [comment]
This is not very fun. Does it happen both on HPC and local executions? 

I wonder how we best find a way around this. Perhaps we need to consider alternatives.

**Comment by abhi18av** [comment]
Oh man, this is a tough nut to crack 🙄 

Okay, so we have a few alternatives 

1. Try thrice and then ignore that particular task, keeping the pipeline alive.

```
errorStrategy { task.attempt<=3 ? 'retry' : 'ignore' }

```

2. Highlight to the users that this is a `known issue`, simply `ignore` all errors in this step and suggest the user ito simply re-run the pipeline with `-resume` option.
3. Think about replacing the underlying software.

**Comment by boulund** [comment]
I think it's hard to pinpoint the issue and report it to original authors, since it runs as expected when run manually, right? I don't feel ready to confidently point out a probable cause for the issue just yet. 

Something deep inside of me still thinks this is related to file system issues somehow. The tool executes so blazingly quickly that Slurm job setup and tear down could constitute a substantial portion of the time spent for that process. This is exactly the type of problem what is worked around with Snakemake using its `--latency-wait` argument, to increase the time waiting for output files to appear in the file system. I don't think Nextflow has that functionality, and as far as I could tell the discussions on that matter doesn't appear to be solved anytime soon.

**Comment by abhi18av** [comment]
Hmm, that's a plausible explanation. I'm curious whether you think we might be able to tackle it by manually delaying (e.g. `sleep 2` ) the process execution to give some time to the overall execution?

Or there might be another way to "warm up" the env?

**Comment by boulund** [comment]
Hmm. Seems a bit hacky, but it's a cheap trick to test a simple sleep delay in bash there, 5-10 seconds?

**Comment by thorellk** [comment]
I guess we should test 10 s then, and if that does not work then that may not be the issue? Or what do you think?

**Comment by boulund** [comment]
Sounds reasonable to me. If it still doesn't work with a 10 second delay then it has got to be something else causing the issues.

**Comment by boulund** [comment]
I just had another hypothesis pop up in my head. Perhaps there is a rate limitation to the official sendsketch server that we're hitting? Is there a way to regulate a single nextflow process to reduce parallelization for that particular step so it doesn't trigger any blocking at the remote server?

**Comment by abhi18av** [comment]
Yup, there's a `maxForks` [process directive](https://www.nextflow.io/docs/latest/process.html#maxforks).

**Comment by thorellk** [comment]
Maybe we should ask the sendsketch developers what they think and how they would suggest to solve it?

**Comment by emilio-r** [comment]
I just tried the sleep 10 approach and while this works better than the retry strategy, in that it does not kill the nextflow run, it still fails some sendsketches (2/16) with the same error that we have seen before.

**Comment by boulund** [comment]
This is so odd. Do you have any good ideas for how we should deal with this? It feels unreasonable to have a step in the pipeline that fails 12% of the time.

**Comment by emilio-r** [comment]
I have written to the sendsketch developers to see if they had some input, but I have yet to receive a reply. I will update you all when I do. 
If we cannot solve the issue or find other approaches to test it, I believe that we have, as @abhi18av say, a limited set of ways forward: either we can just acknowledge that it is a known bug, keep testing, try to solve it long-term, and suggest the user to resume; or we can change sendsketch to something we know is more robust.

**Comment by boulund** [comment]
I am not aware of any other tools for species identification that is as low-memory and low-cpu. That would probably be mash or Kraken2? Which is kind of what we wanted to avoid in the first place :D

**Comment by abhi18av** [comment]
Oh, it seems like this is a chicken-and-egg problem. If it'd be okay with the team, I think that we should continue with the merge and acknowledge - for the time being - that this is a known issue. 

We can try to tweak the `errorStrategy`  in a more sophisticated way to find a better solution.

P.S. Apologies for the absence here, a lot was going on in my personal life 💒 and now I have a bit more time again.

**Comment by boulund** [comment]
To acknowledge this as a known issue and leave some kind of mention about it in the release documentation sounds ok to. We should also create an issue labeled with "Bug" to reference this issue, so other users easily can see that it's acknowledged issue that is being worked on.

**Comment by thorellk** [comment]
I agree with @boulund and @abhi18av, but I think we should improve the error strategy so that prokka is running without the -gram option if sendsketch fails and with genus "n/a" and species "n/a" or something so that the pipeline still completes producing output files for all samples.

**Comment by abhi18av** [comment]
Hi @thorellk,

> ...prokka is running without the -gram option if sendsketch fails and with genus "n/a" and species "n/a" or something so that the pipeline still completes producing output files for all samples.

The only concern I have with this is that this makes things `implicit` as opposed to being `explicit` to the users. In any case, if this seems like the right direction I'd be happy to add that to the project.

**Comment by boulund** [comment]
Wouldn't it be possible to issue some kind of warning in the log to highlight to the end user that even if the pipeline completed, there were potential issues with the run?

**Comment by emilio-r** [comment]
After having had some major HPC issues for the past few weeks, I am once again able to run scale BACTpipe testing. Unfortunately, I have yet to get any feedback from the Sendsketch devs. So, once we have implemented something akin to what @thorellk suggests, tell me, and I will run some testing and get back to you. Once implemented and tested we could perhaps see to #137.

**Comment by boulund** [comment]
I just realized I forgot to update the BACTpipe diagram now that we replaced sendsketch with kraken2. Can someone help me get that sorted here in the dev branch? @emilio-r  perhaps?

**Comment by emilio-r** [comment]
No problem @boulund, I will see to it on Monday.

**Comment by boulund** [comment]
Looking good @emilio-r ! Great! 

Perhaps we should change it from "contamination screening" to "taxonomic classification" or something like that ?

I chose the name of the kraken2 module I implemented to be `classify_taxonomy` instead of anything like contamination screening, thinking it is a bit more general and easy to understand. Of course, it can still be used for the same purpose, but it's a bit more general now that it actually provides a complete profile of a sample (and estimates the species) instead of just determining if it's contaminated or not.

**Comment by emilio-r** [comment]
Sure! I also realized that I had missed that `Kraken2` takes reads now, not contigs as `SendSketch` did. I remade the flowchart to follow these two points. Unfortunately, I have been unable to test the branch today as the HPC is back to experiencing issues that are making working there impossible. I will try to run it during the night to see if that is possible.

**Comment by boulund** [comment]
Good that you saw it, I completely overlooked that part in the last version of the graph 😄 .

Best of luck running on Rackham, the system seems to be in a bad mood recently...

**Comment by emilio-r** [comment]
Hi again! A smallish update about me testing the develop-branch: I've now been able to squeeze through a couple of tests on the HPC and can report that running without -kraken2_db works like a charm where all entered samples pass through taking just 40 minutes for running 15 samples. However, when running with this Kraken2_db I am consistently seeing issues like this:


```
============================================================
         BACTpipe workflow completed without errors         
               Check output files in folder:                
                      BACTpipe_results                      
============================================================
WARN: Killing pending tasks (13)

executor >  slurm (15)
[1d/061c41] process > FASTP (CAN-152_S19_L001) [100%] 2 of 2
[-        ] process > CLASSIFY_TAXONOMY        -
[-        ] process > SHOVILL                  -
[-        ] process > ASSEMBLY_STATS           -
[-        ] process > PROKKA                   -
[-        ] process > MULTIQC                  -
Creating Conda env: bioconda::shovill python=3.6.8 [cache /crex/proj/uppstore2017270/Emilio/bactpipe-testing/210419/test-210503/with-kraken/work/conda/env-f80473f116e7c53b889c8479b0def09c]
Creating Conda env: bioconda::kraken2 python=3.6.8 [cache /crex/proj/uppstore2017270/Emilio/bactpipe-testing/210419/test-210503/with-kraken/work/conda/env-57f9cf615d5dadc328bb6c1fafe7cacd]
Oops... Pipeline execution stopped with the following message: null
Error executing process > 'CLASSIFY_TAXONOMY (139_S57_L001)'

Caused by:
  Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /crex/proj/uppstore2017270/Emilio/bactpipe-testing/210419/test-210503/with-kraken/work/conda/env-57f9cf615d5dadc328bb6c1fafe7cacd bioconda::kraken2 python=3.6.8
  status : 127
  message:
    bash: conda: command not found

```

It is likely that the Crex read/write issues are the culprit here as Conda works fine without the Kraken2_db loaded:

```
============================================================
         BACTpipe workflow completed without errors         
               Check output files in folder:                
                      BACTpipe_results                      
============================================================

executor >  slurm (76)
[67/d60212] process > FASTP (CAN-152_S19_L001)       [100%] 15 of 15 ✔
[25/bcaa78] process > CLASSIFY_TAXONOMY (CAN-152_... [100%] 15 of 15 ✔
[3a/834425] process > SHOVILL (S-50_S59_L001)        [100%] 15 of 15 ✔
[61/48e100] process > ASSEMBLY_STATS (S-50_S59_L001) [100%] 15 of 15 ✔
[1d/0d592c] process > PROKKA (CAN-152_S19_L001)      [100%] 15 of 15 ✔
[14/dc5fb7] process > MULTIQC                        [100%] 1 of 1 ✔
============================================================
         BACTpipe workflow completed without errors         
               Check output files in folder:                
                      BACTpipe_results                      
============================================================
Completed at: 03-May-2021 09:10:09
Duration    : 40m 19s
CPU hours   : 11.9
Succeeded   : 76

```
Hopefully Wednesday's upcoming maintenence will finally fix the filesystem and I can test this for real.

**Comment by boulund** [comment]
It looks like it's complaining about not finding conda. Are you sure the conda module on uppmax is loaded properly?



Fredrik Boulund | Head of Bioinformatics
Centre for Trmaybe anslational Microbiome Research | MTC | Karolinska Institutet
171 77 Stockholm | Solnavägen 9
+46 73 843 1649
________________________________
Från: emilio-r ***@***.***>
Skickat: den 3 maj 2021 12:25
Till: ctmrbio/BACTpipe ***@***.***>
Kopia: Fredrik Boulund ***@***.***>; Mention ***@***.***>
Ämne: Re: [ctmrbio/BACTpipe] Develop (#160)


Hi again! A smallish update about me testing the develop-branch: I've now been able to squeeze through a couple of tests on the HPC and can report that running without -kraken2_db works like a charm where all entered samples pass through taking just 40 minutes for running 15 samples. However, when running with this Kraken2_db I am consistently seeing issues like this:

============================================================

         BACTpipe workflow completed without errors

               Check output files in folder:

                      BACTpipe_results

============================================================

WARN: Killing pending tasks (13)



executor >  slurm (15)

[1d/061c41] process > FASTP (CAN-152_S19_L001) [100%] 2 of 2

[-        ] process > CLASSIFY_TAXONOMY        -

[-        ] process > SHOVILL                  -

[-        ] process > ASSEMBLY_STATS           -

[-        ] process > PROKKA                   -

[-        ] process > MULTIQC                  -

Creating Conda env: bioconda::shovill python=3.6.8 [cache /crex/proj/uppstore2017270/Emilio/bactpipe-testing/210419/test-210503/with-kraken/work/conda/env-f80473f116e7c53b889c8479b0def09c]

Creating Conda env: bioconda::kraken2 python=3.6.8 [cache /crex/proj/uppstore2017270/Emilio/bactpipe-testing/210419/test-210503/with-kraken/work/conda/env-57f9cf615d5dadc328bb6c1fafe7cacd]

Oops... Pipeline execution stopped with the following message: null

Error executing process > 'CLASSIFY_TAXONOMY (139_S57_L001)'



Caused by:

  Failed to create Conda environment

  command: conda create --mkdir --yes --quiet --prefix /crex/proj/uppstore2017270/Emilio/bactpipe-testing/210419/test-210503/with-kraken/work/conda/env-57f9cf615d5dadc328bb6c1fafe7cacd bioconda::kraken2 python=3.6.8

  status : 127

  message:

    bash: conda: command not found





It is likely that the Crex read/write issues are the culprit here as Conda works fine without the Kraken2_db loaded:

============================================================

         BACTpipe workflow completed without errors

               Check output files in folder:

                      BACTpipe_results

============================================================



executor >  slurm (76)

[67/d60212] process > FASTP (CAN-152_S19_L001)       [100%] 15 of 15 ✔

[25/bcaa78] process > CLASSIFY_TAXONOMY (CAN-152_... [100%] 15 of 15 ✔

[3a/834425] process > SHOVILL (S-50_S59_L001)        [100%] 15 of 15 ✔

[61/48e100] process > ASSEMBLY_STATS (S-50_S59_L001) [100%] 15 of 15 ✔

[1d/0d592c] process > PROKKA (CAN-152_S19_L001)      [100%] 15 of 15 ✔

[14/dc5fb7] process > MULTIQC                        [100%] 1 of 1 ✔

============================================================

         BACTpipe workflow completed without errors

               Check output files in folder:

                      BACTpipe_results

============================================================

Completed at: 03-May-2021 09:10:09

Duration    : 40m 19s

CPU hours   : 11.9

Succeeded   : 76





Hopefully Wednesday's upcoming maintenence will finally fix the filesystem and I can test this for real.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fctmrbio%2FBACTpipe%2Fpull%2F160%23issuecomment-831169803&data=04%7C01%7Cfredrik.boulund%40ki.se%7C6772e0760f4543d7eca508d90e1dd636%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637556343578792564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=guL0OFz2dMwRQ%2FQOZjOWC8sULEDswNsY74wsSWxPi0g%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABFRA2SHFS3OI24NJZIZFSDTLZ23FANCNFSM4X4KGUBA&data=04%7C01%7Cfredrik.boulund%40ki.se%7C6772e0760f4543d7eca508d90e1dd636%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637556343578802517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yW9hw6aKV97hfjuXPFob8fVVUJXP%2FhN%2FrYgBuaVoEx0%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by emilio-r** [comment]
The Conda module is loaded in the same way between both of the attached log snippets. The only difference in how i load them is that when it fails to load I also copy the `Kraken2` database to scratch.

**Comment by boulund** [comment]
A whole hour just to run kraken2 (on a good day)?? 
Wow, that's crazy. Running kraken2 on a normal bacterial isolate sample should only take a few minutes at most. Do you really need to copy the database to scratch to run it on UPPMAX? Kraken2 normally just loads the entire database into memory, meaning it's pretty much equivalent to a single linear read from the shared storage, so the total IO load will be the same regardless if it's copied or not, with the drawback that copying it will in all cases be slower since it has to write all the copied data to the local scratch disk, then read it into memory again (even if I think the Linux file system cache might do something clever hear to minimize that extra cost).

**Comment by thorellk** [comment]
I agree with @boulund that it doesn't really make sense to copy the database to scratch. In a case when one runs multiple kraken analyses in the same job, it makes more sense but since nextflow submits one job per process, I guess nothing is gained by this?

**Comment by emilio-r** [comment]
@boulund, Looking back at some previous runs of Kraken2 then yes, it took me 36 minutes to run it, including loading the database this way. It may be relevant to also mention that this was for assessing some 700 samples in one job...

I used this approach as Uppmax themselves recommend copying it to a scratch variable when running Kraken2 there, and that is how we have been running it ourselves. However, by now skipping that and just using the directory as specified by the module (and luckily managing to avoid the Crex issues) I just finished a run with my test samples, using the kraken2_db flag. All 15/15 passed through the pipe without issues! As before, I'll now see if I can run it over a larger sample size, but it works fine on this set.

**Comment by emilio-r** [comment]
This morning I managed to test the develop-branch on a full plate:
```
executor >  slurm (471)
[1b/3f6c89] process > FASTP (vz3_S50_L001)           [100%] 96 of 96 ✔
[57/b1cce0] process > CLASSIFY_TAXONOMY (ausabrp1... [100%] 96 of 96 ✔
[9a/450dc1] process > SHOVILL (Undetermined_S0_L001) [100%] 96 of 96, failed:...
[13/5d7c4b] process > ASSEMBLY_STATS (ausabrp105_... [100%] 91 of 91 ✔
[0f/e643f4] process > PROKKA (Nentsy15_S69_L001)     [100%] 91 of 91 ✔
[0e/66123d] process > MULTIQC                        [100%] 1 of 1 ✔
============================================================
         BACTpipe workflow completed without errors         
               Check output files in folder:                
                      BACTpipe_results                      
============================================================
Completed at: 04-May-2021 07:53:47
Duration    : 56m 4s
CPU hours   : 68.4 (17.9% failed)
Succeeded   : 466
Ignored     : 5
Failed      : 5
```
The ones that failed Shovill here, were either timed out (Crex issues?) or had too few reads for assembly. I'm happy to say that the branch appears to work fine on the HPC, either with or without the kraken database!

**Review by emilio-r — APPROVED** [review]
I'm happy to report that from testing the branch, everything seems to work fine!

**Comment by boulund** [comment]
Fantastic news! Then I guess it's time for a final check of everything, please help me to verify and fill in if I missed something important:

- [x] Everything runs as intended
- [ ] Suitable user-friendly error messages are printed on user errors (no input, not entering database paths, etc)
- [ ] The README is up-to-date, including the flowchart diagram
- [ ] The docs are up-to-date, is there anything mentioned about which kraken2 database we recommend using with BACTpipe?
- [ ] All version numbers in the docs and elsewhere in the dev branch are bumped to the latest version (I think this should be version `3.1.0`, is that right?)
- [ ] The CHANGELOG is updated to reflect recent changes that affects end users
- [ ] The default profile work as intended, both for local execution, and for UPPMAX Rackham
- [ ] The Docker profiles work as intended. 
- [ ] Are we good-to-go for using the workflow in NF Tower @abhi18av ?
- [ ] ... anything I missed? Please comment below

**Comment by abhi18av** [comment]
Hi team 😊 

> The Docker profiles work as intended.

This would need to be updated to accomodate the recent changes. Will open up a PR by tonight :) 

> Are we good-to-go for using the workflow in NF Tower @abhi18av ?

Yes, but I'd submit a patch for this once the latest release of Tower is publicly available to make sure that this is stable.


Warmly,
Abhinav

**Comment by emilio-r** [comment]
> The default profiles work as intended, both for local execution and for UPPMAX Rackham. 

I just finished a run using the local config on Rackham and everything except MultiQC worked:
```
executor >  local (76)
[24/11597e] process > FASTP (CAN-152_S19_L001)       [100%] 15 of 15 ✔
[36/a7b95e] process > CLASSIFY_TAXONOMY (CAN-152_... [100%] 15 of 15 ✔
[7d/c61511] process > SHOVILL (TuvaB41_S2_L001)      [100%] 15 of 15 ✔
[1a/158a8d] process > ASSEMBLY_STATS (TuvaB41_S2_... [100%] 15 of 15 ✔
[41/233b5a] process > PROKKA (TuvaB41_S2_L001)       [100%] 15 of 15 ✔
[cc/16c7dd] process > MULTIQC                        [100%] 1 of 1, failed: 1 ✔
============================================================
         BACTpipe workflow completed without errors         
               Check output files in folder:                
                      BACTpipe_results                      
============================================================
[cc/16c7dd] NOTE: Process `MULTIQC` terminated with an error exit status (1) -- Error is ignored
Completed at: 04-May-2021 13:10:30
Duration    : 2h 41m 57s
CPU hours   : 10.4 (0% failed)
Succeeded   : 75
Ignored     : 1
Failed      : 1
```
```
[emilir@rackham2 local]$ cat work/cc/16c7dda72d6d4ecf4c4a23306c5479/.command.err
Traceback (most recent call last):
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import multiqc
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/multiqc/__init__.py", line 16, in <module>
    from .multiqc import run
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/multiqc/multiqc.py", line 39, in <module>
    from .plots import table
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/multiqc/plots/table.py", line 9, in <module>
    from multiqc.utils import config, report, util_functions, mqc_colour
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/multiqc/utils/mqc_colour.py", line 7, in <module>
    import spectra
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/spectra/__init__.py", line 1, in <module>
    from .core import COLOR_SPACES, Color, Scale
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/spectra/core.py", line 1, in <module>
    from colormath import color_objects, color_conversions
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/colormath/color_conversions.py", line 13, in <module>
    import networkx
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/crex/proj/uppstore2017270/Emilio/bactpipe-testing/210503/testing/local/work/conda/env-3abca7a24ea4d6c708bf4c6cea6413d2/lib/python3.9/fractions.py)
```
From what I can tell this is MultiQC trying to get a package (gcd) that is in another module. Could it be a issue with MultiQC version? It will be interesting to see if you see this too when running this config.

> including the flowchart diagram

This has been updated to future 3.1 release.

**Comment by boulund** [comment]
It seems that is an issue with dependencies in MultiQC with newer Python versions. It seems we can pin python to 3.8 to work around it for now.
https://www.biostars.org/p/9465438/#9465448

**Comment by boulund** [comment]
I think we're very close to completing this now! Has anyone encountered any odd error messages that were not handled gracefully? 

I'll make one last check to see if version numbers of correct everywhere.

**Comment by boulund** [comment]
Sorry for putting all these commit directly on the develop branch, I started with a very small change, but found lots of minor things I wanted to improve across the documentation.

**Comment by emilio-r** [comment]
> odd error messages that were not handled gracefully

As comes to mind, some errors that affect the end user may be:
- Not having a profile assigned. Most users would either want to have local or Docker so maybe we should then say that if none is specifically assigned, local will be run as default?
- Not assigning a Kraken2 database and that this will skip that module.
- Running an outdated Nextflow version and getting the stub-error, or some other related error.
- Not having SignalP installed (but this will be applied in a later version) 
- That the BACTpipe arguments are incorrectly entered (paths not in quotes, empty, etc.)

**Comment by boulund** [comment]
> * Not having a profile assigned. Most users would either want to have local or Docker so maybe we should then say that if none is specifically assigned, local will be run as default?
This is mentioned in the docs, in this section: https://bactpipe.readthedocs.io/en/develop/running.html#running-bactpipe

Additionally, if running a cluster profile that requires a project name, BACTpipe throws an error message. E.g. if the Rackham profile is selected but no `--project` is given. This is also mentioned here: https://bactpipe.readthedocs.io/en/develop/running.html#profiles.

Example:
```
$ nextflow run ~/bactpipe/bactpipe.nf --kraken2_db /db/kraken2/minikraken2_v
2_8GB_201904_UPDATE/ --reads 'raw_data/V300034817/subset/*_{1,2}.fq.gz' -profile rackham
N E X T F L O W  ~  version 21.04.0
Launching `/ceph/home/boulund/bactpipe/bactpipe.nf` [shrivelled_knuth] - revision: f2910af028
============================================================
                          BACTpipe
                       Version 3.1.0
          Bacterial whole genome analysis pipeline
              https://bactpipe.readthedocs.io
============================================================
BACTpipe requires that you set the 'project' parameter when running the rackham profile.
Specify --project <project_name> on the command line, or add it to a custom configuration file.Refer to the official docs for more information.
```

> * Not assigning a Kraken2 database and that this will skip that module.
BACTpipe prints a warning about it, and it is mentioned in the docs and implied in the command line help. 

Example:
```
(base) [boulund@c1hitachi10 BACTpipe_test]$ nextflow run ~/bactpipe/bactpipe.nf --reads 'raw_data/V300034817/subset/*_
{1,2}.fq.gz'
N E X T F L O W  ~  version 21.04.0
Launching `/ceph/home/boulund/bactpipe/bactpipe.nf` [jolly_volhard] - revision: f2910af028
============================================================
                          BACTpipe
                       Version 3.1.0
          Bacterial whole genome analysis pipeline
              https://bactpipe.readthedocs.io
============================================================
            Running with the following settings:
                       reads: raw_data/V300034817/subset/*_{1,2}.fq.gz
                     project:
              clusterOptions: false
                  output_dir: BACTpipe_results
                  kraken2_db:
          kraken2_confidence: 0.5
      kraken2_min_proportion: 1.00
               shovill_depth: 100
               shovill_kmers: 31,33,55,77,99,127
              shovill_minlen: 500
               prokka_evalue: 1e-09
              prokka_kingdom: Bacteria
            prokka_reference:
      prokka_signal_peptides: true
          keep_trimmed_fastq: false
         keep_shovill_output: false
============================================================
WARN: No Kraken2 database specified. Use --kraken2_db /path/to/db to use Kraken2 to classify samples and determine gra
m stain.
[-        ] process > FASTP             -
[-        ] process > CLASSIFY_TAXONOMY -
[-        ] process > SHOVILL           -
... etc
```

> * Running an outdated Nextflow version and getting the stub-error, or some other related error.
Not sure about this one. We do have this line here, but not sure if that is actually enforced or what kind of error message is printed if an old version is used: https://github.com/ctmrbio/BACTpipe/blob/develop/nextflow.config#L8

> * Not having SignalP installed (but this will be applied in a later version)
This issue is still open I think and has been pushed to our next release: https://github.com/ctmrbio/BACTpipe/issues/148

> * That the BACTpipe arguments are incorrectly entered (paths not in quotes, empty, etc.)
This is _kind of_ fixed, but still has a minor bug (the workflow completed "without errors" even if it failed 😄 ...
```
(base) [boulund@c1hitachi10 BACTpipe_test]$ nextflow run ~/bactpipe/bactpipe.nf
N E X T F L O W  ~  version 21.04.0
Launching `/ceph/home/boulund/bactpipe/bactpipe.nf` [maniac_mclean] - revision: f2910af028
============================================================
                          BACTpipe
                       Version 3.1.0
          Bacterial whole genome analysis pipeline
              https://bactpipe.readthedocs.io
============================================================
            Running with the following settings:
                     project:
              clusterOptions: false
                  output_dir: BACTpipe_results
                       reads:
                  kraken2_db:
          kraken2_confidence: 0.5
      kraken2_min_proportion: 1.00
               shovill_depth: 100
               shovill_kmers: 31,33,55,77,99,127
              shovill_minlen: 500
               prokka_evalue: 1e-09
              prokka_kingdom: Bacteria
            prokka_reference:
      prokka_signal_peptides: true
          keep_trimmed_fastq: false
         keep_shovill_output: false
============================================================
WARN: No Kraken2 database specified. Use --kraken2_db /path/to/db to use Kraken2 to classify samples and determine gra
m stain.
Path string cannot be empty


Cannot find any reads matching: ''
Did you specify --reads 'path/to/*_{1,2}.fastq.gz'? (note the single quotes)
Specify --help for a summary of available commands. Refer to the official docs for more information.



  Example usage:
    nextflow run ctmrbio/BACTpipe --reads '*_R{1,2}.fastq.gz'

  Mandatory arguments:
    --reads                 Path to input data (must be surrounded with single quotes).

  Optional arguments:
    --kraken2_db            Path to Kraken2 database for taxonomic classification and gram
                            stain determination (recommended!).
    --keep_trimmed_fastq    Save trimmed fastq files in output directory (default: false).
    --keep_shovill_output   Save all shovill output in output directory (default: false).

  Output options:
    --output_dir            Output directory, where results will be saved
                            (default: BACTpipe_results).

  Refer to the online manual for more information and all available options:
             https://bactpipe.readthedocs.io

============================================================
         BACTpipe workflow completed without errors
Oops... Pipeline execution stopped with the following message: Path string cannot be empty
Path string cannot be empty
```

**Comment by boulund** [comment]
I'm happy with how this works now. Let me know if you think otherwise. We can merge later today or tomorrow unless there is anything else.

**Review by boulund — APPROVED** [review]

**Review by abhi18av — APPROVED** [review]
I'm happy with the changes for this release as well 👍

**Comment by emilio-r** [comment]
I am also happy with the way this looks and behaves, so I reaffirm my previous approval of this merge.

**Pull request merged**
