### PR TITLE
Replace sendsketch with kraken2

### PR DESCRIPTION
**Pull request by boulund**
Building on the work by @abhi18av to fix SignalP params and dockerize the workflow.

This PR is still work in progress:
* I replaced SendSketch with Kraken2, and opted to place Kraken2 directly after Fastp so it can be run in parallel with the assembly step. There is no real reason to run Kraken2 on the contigs instead of the reads.
* I have to add some parsing to read the results from the Kraken2 report. 
* We were planning that Kraken2 can be skipped entirely if no database path is given for the parameter `kraken2_db`. I have not implemented that yet. Then we just forward some dummy output downstream the pipeline so the prokka step can run without gram stain and genus+species info.

Currently, on my test data sets I got the following results from running the following awk command on the kraken2 report:

```
awk '{if ($1 > MIN_PROPORTION && $4 == "S") print $0}'
```
if `MIN_PROPORTION` is set to e.g. 50.00 (50%). 

One sample, clearly `Campylobacter coli`:
```
74.80  1496060 1477469 S       195                       Campylobacter coli
```
On another, clearly `Campylobacter jejuni`:
```
67.96  1359145 1342906 S       197                       Campylobacter jejuni 
```
On this other contaminated sample, the proportions are much lower and risk being classified as several (I had to lower `MIN_PROPORTION` for this to show anything at all):
```
5.72  114463  113736  S       562                     Escherichia coli
7.91  158280  158280  S       585                     Proteus vulgaris
5.18  103621  101663  S       584                     Proteus mirabilis
```

To produce input data for the prokka step, we should be able to just use something akin to that awk command to easily get the classified species in the sample. If the output contains more than one row: it's contaminated. If it's only one row: use that species assignment, and get the gram stain from our little "database". Does that sound ok @thorellk ? 

I'll rewrite/write a new python script to do that processing so it's as streamlined as possible.

### CODE REVIEW

**Comment by boulund** [comment]
I think this is ready for merging now @thorellk, @abhi18av, @emilio-r 

Let me know if you want to take it for a test spin! 

I think it should work as we want it now. Let me know if you encounter anything strange!

**Comment by thorellk** [comment]
Ok, should we then merge to develop and then @emilio-r can test it on rackham/snowy and I could test it locally on my laptop?

**Comment by boulund** [comment]
Great idea! I have merged this branch to develop now.

I should probably clarify how the taxonomic classification algorithm works:
```
def classify(detected_species, min_proportion, gramstain_db):
    taxon_names = [
            species for proportion, species in 
            filter(lambda x: x[0] > min_proportion, detected_species)
    ]

    output_genus = "Unknown"
    output_species = "unknown"

    genera = set(genus for genus, species in taxon_names)
    if len(genera) > 1:
        output_genus = "Mixed"
    elif len(genera) == 1:
        output_genus = genera.pop()

    species = set(species for genus, species in taxon_names)
    if (len(species) > 1) and output_genus:
        output_species = "spp."
    elif len(species) == 1:
        output_species = species.pop()

    output_gramstain = gramstain_db.get(output_genus, "Unknown")

    return output_genus, output_species, output_gramstain
```

* If there is only one species with proportion greater than `min_proportion` then it is output as `Genus species pos` (for a gram-positive genus). 
* If there are more than one genera in the sample, they are called `Mixed spp. Unknown` (we don't assign gram stain for mixed samples).
* If there are multiple species from the same genus in the sample, output is `Genus spp. pos` (for a gram-positive genus).
* If there are no species above the `min_proportion` threshold it will be called `Unknown unknown Unknown` (everything is unknown).

I hope this feels natural and intuitive.

**Comment by abhi18av** [comment]
Hey @boulund and @thorellk , this does look nice!

Just to highlight that this merge closed the https://github.com/ctmrbio/BACTpipe/pull/161 automatically since it was essentially duplicate code at the moment.

I'm looking forward to the results of BACTpipe on the cluster (locally, I think it should work fine)  - just to avoid issues similar to `sendsketch` or something else and once that's done I'll complete the docker profile and make the workflow Tower friendly.

**Comment by emilio-r** [comment]
Great job @boulund! Although a part of me dearly wanted to solve the Sendsketch issues, I think it is the correct move to use something else here. From my own experience with it, I believe that kraken2 is reliable. I will pull this and run some HPC testing on Monday morning. I’ll get back to you all then with the results!

**Comment by boulund** [comment]
@abhi18av Oh, I didn't realize you were done with the work in that branch! I thought there was still more commits incoming on that branch. But great, two birds with one stone then! :)

**Pull request merged**
