### PR TITLE
Hotfix for syncing input for prokka

### PR DESCRIPTION
**Pull request by abhi18av**
Hi team,

This PR implements the hotfix for making sure that the inputs for `prokka` are from the same samples.

Instead of 2 channels, `PROKKA` now receives a single channel with the following shape 

```nextflow
    tuple val(pair_id), path(contigs_file), path(classification)
```

I did a `stub-run` with mock data and confirmed that the channel values which are being passed to `PROKKA` are a tuple of values from `SHOVILL` and `CLASSIFY_TAXONOMY` processes.

```

[CCUG-74904, /Users/eklavya/projects/code/BACTpipe/work/90/b9b32bb95a5e328ca5856d5d3925fc/CCUG-74904_contigs.fa, /Users/eklavya/projects/code/BACTpipe/work/b6/479600771319922e7213ed75a07c04/CCUG-74904.classification.txt]
[H-Felis-CS1, /Users/eklavya/projects/code/BACTpipe/work/63/b1f65b727e6fefb8ca49e852766bbb/H-Felis-CS1_contigs.fa, /Users/eklavya/projects/code/BACTpipe/work/c2/21b607a036b7059998f8e999003c33/H-Felis-CS1.classification.txt]
[CCUG-26476, /Users/eklavya/projects/code/BACTpipe/work/26/d660bb6c2424e3642a578c3f96cf32/CCUG-26476_contigs.fa, /Users/eklavya/projects/code/BACTpipe/work/0e/986bcd68ffb2d1177b447b3be9ebff/CCUG-26476.classification.txt]
[CCUG-74956, /Users/eklavya/projects/code/BACTpipe/work/5a/36c6255cb3ca3f5d0e92a11e51f70c/CCUG-74956_contigs.fa, /Users/eklavya/projects/code/BACTpipe/work/22/b24ddd8251aab03d81dab071b96499/CCUG-74956.classification.txt]
[CCUG-72405, /Users/eklavya/projects/code/BACTpipe/work/cf/13c32c54621c4e16bf46f50deede2b/CCUG-72405_contigs.fa, /Users/eklavya/projects/code/BACTpipe/work/51/cdd9dab45bb4ceb32faae8b8f62a8e/CCUG-72405.classification.txt]
[it162, /Users/eklavya/projects/code/BACTpipe/work/74/9024776bd6f0f4129471a3bc695204/it162_contigs.fa, /Users/eklavya/projects/code/BACTpipe/work/2b/c3bd1c41b0b2ab4f80b24b6ade2297/it162.classification.txt]
[CCUG-74566, /Users/eklavya/projects/code/BACTpipe/work/46/47f6a7649871f4d2b11bf00f19b11e/CCUG-74566_contigs.fa, /Users/eklavya/projects/code/BACTpipe/work/39/f08e68f832cedc453f38f400924ea3/CCUG-74566.classification.txt]
[CCUG-30872, /Users/eklavya/projects/code/BACTpipe/work/be/ae0c5b5e00f704db9fc1bd0e0de545/CCUG-30872_contigs.fa, /Users/eklavya/projects/code/BACTpipe/work/48/2017e902608c0b506649ce25bd0c7e/CCUG-30872.classification.txt]
[CCUG-33000, /Users/eklavya/projects/code/BACTpipe/work/2a/008dd2c159cbaf33534b0b17edf0aa/CCUG-33000_contigs.fa, /Users/eklavya/projects/code/BACTpipe/work/d3/7b482d191f3f145d46d2c3bf648a87/CCUG-33000.classification.txt]
[A-salmonicida, /Users/eklavya/projects/code/BACTpipe/work/89/4c7755c04d1b416c5ad512c7b73fda/A-salmonicida_contigs.fa, /Users/eklavya/projects/code/BACTpipe/work/74/21dfbf2267a6133944c680d0ef120a/A-salmonicida.classification.txt]
```

### CODE REVIEW

**Comment by thorellk** [comment]
Testing it now :)

**Comment by boulund** [comment]
Awesome @abhi18av!

How did the testing go @thorellk ?

**Comment by thorellk** [comment]
I wrote an update in the issue #171

**Comment by boulund** [comment]
?

Odd if it doesn't run prokka at all?

**Comment by thorellk** [comment]
Haha, yes, pull request 171, issue #170 

No, it doesn't seem to run prokka at all. No error messages as far as I can see...
[BACTpipe_CAN-CCUG_210622.txt](https://github.com/ctmrbio/BACTpipe/files/6702483/BACTpipe_CAN-CCUG_210622.txt)
[nextflow.log](https://github.com/ctmrbio/BACTpipe/files/6702485/nextflow.log)

**Comment by boulund** [comment]
Did we forget to update the output section of the classify_taxonomy process? I can't see anything about it in the diff for this PR.

**Comment by abhi18av** [comment]
I'm not sure that it's related to classify_taxonomy - but I'm looking into it now 🤔

**Comment by boulund** [comment]
I would guess the `Channel.join` requires the input data to have a key that it can join the two streams on, and if we didn't change the output of `CLASSIFY_TAXONOMY` will not have the `sample_id` key in the output channel?

**Comment by abhi18av** [comment]
@boulund you are definitely hawk eyes 🦅 

We do need the `sample_id` in the output for `classify_taxonomy` and once that is there, the `join` uses the first field by default to join these streams.

With the fix, it seems to work 

```
executor >  local (16)
[07/8c1946] process > FASTP (it162)                [100%] 3 of 3 ✔
[91/0b4537] process > CLASSIFY_TAXONOMY (it162)    [100%] 3 of 3 ✔
executor >  local (16)
[07/8c1946] process > FASTP (it162)                [100%] 3 of 3 ✔
[91/0b4537] process > CLASSIFY_TAXONOMY (it162)    [100%] 3 of 3 ✔
[cb/3ba0aa] process > SHOVILL (it162)              [100%] 3 of 3 ✔
[cc/77a9b7] process > ASSEMBLY_STATS (H-Felis-CS1) [100%] 3 of 3 ✔
[ef/7afb03] process > PROKKA (it162)               [100%] 3 of 3 ✔
[e4/8731f0] process > MULTIQC                      [100%] 1 of 1 ✔
============================================================
         BACTpipe workflow completed without errors         
               Check output files in folder:                
                      BACTpipe_results                      
============================================================
WARN: Task runtime metrics are not reported when using macOS without a container engine



```

I didn't cherry pick all the changes I tried in a seperate branch previously (used to generate the output in https://github.com/ctmrbio/BACTpipe/pull/171#issue-672738876)  🤦

**Comment by thorellk** [comment]
Great, testing it now :)

**Comment by abhi18av** [comment]
Hi @thorellk ,

Could you please let us know if this worked as expected?

**Comment by thorellk** [comment]
I would love to but our HPC throws seemingly random conda errors at me :( Tomorrow when I am on more stable internet I will download some data to my laptop and run from there. Sorry for the delay...

**Comment by abhi18av** [comment]
Oh, okay. I understand Kaisa, no worries :)

**Comment by thorellk** [comment]
Now I've ran it on my laptop, works like a charm :)

**Pull request merged**
